k8s_version: v1.17.3
k3s_version: "{{ k8s_version }}+k3s1"
ansible_user: root
systemd_dir: /etc/systemd/system
url_k3s_release: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s

master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""