---

- name: Delete k3s if already present
  file:
    path: /usr/local/bin/k3s
    state: absent

- name: Download k3s binary x64
  get_url:
      url: {{ url_k3s_release }}
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
#  when: ( ansible_facts.userspace_architecture == "x86_64" )
  when: ( ansible_facts.architecture == "x86_64" )
